from typing import Optional, List
from fastapi import FastAPI, Depends, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from pydantic import BaseModel

import os
import models
from database import engine, get_db

models.Base.metadata.create_all(bind=engine)

app = FastAPI()

origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ProjectCreate(BaseModel):
    name: str
    description: Optional[str] = None

class ProjectResponse(BaseModel):
    id: int
    name: str
    description: Optional[str] = None

    class Config:
        from_attributes = True # Allows Pydantic to read SQLAlchemy objects


@app.get("/")
def root():
    return {"message": "SQLAlchemy Backend is running!"}

@app.post("/projects", response_model=ProjectResponse)
def create_project_route(project: ProjectCreate, db: Session = Depends(get_db)):
    # Create the SQLAlchemy object
    # user_id parameter disabled for now
    new_project = models.Project(name=project.name, description=project.description)
    db.add(new_project)
    db.commit()
    db.refresh(new_project) # Get the new ID generated by SQLite
    return new_project

@app.get("/projects", response_model=List[ProjectResponse])
def get_projects_route(db: Session = Depends(get_db)):
    projects = db.query(models.Project).order_by(models.Project.id.desc()).all()
    return projects

@app.get("/projects/{project_id}")
def get_project(project_id: int, db: Session = Depends(get_db)):
    project = db.query(models.Project).filter(models.Project.id == project_id).first()
    if not project:
        return {"error": "Project not found"}
    return {"name": project.name}


@app.post("/projects/{project_id}/documents/")
async def upload_documents(project_id: int, files: List[UploadFile] = File(...), db: Session = Depends(get_db)):

    ALLOWED_EXTENSIONS = {".txt", ".md", ".rtf"}
    successful_uploads = []
    failed_uploads = []
    
    for file in files:

        _, ext = os.path.splitext(file.filename)

        if ext.lower() not in ALLOWED_EXTENSIONS:
           failed_uploads.append({"filename": file.filename, "reason": "Unsupported file type"})
           continue
        
        try:
            # 1. Read the file
            content = await file.read()
            text_content = content.decode("utf-8") 
            file_type = ext.lower().lstrip(".") or "text"
            
            # 2. Create the Document object
            new_doc = models.Document(
                project_id=project_id,
                filename=file.filename,
                content=text_content,
                type=file_type
            )
            
            db.add(new_doc)
            successful_uploads.append(file.filename)

        except UnicodeDecodeError:
            failed_uploads.append({"filename": file.filename, "reason": "Unreadable text encoding"})
        except Exception as e:
           
            failed_uploads.append({"filename": file.filename, "reason": "Corrupted file"})
        
    # Commit all files to the database at once!
    db.commit()
    
    return {"message": f"Successfully uploaded {len(files)} files!", "successful": successful_uploads, "failed": failed_uploads}

@app.get("/projects/{project_id}/documents/")
def get_project_documents(project_id: int, db: Session = Depends(get_db)):
   
    documents = db.query(models.Document).filter(models.Document.project_id == project_id).all()
    
    return [{"id": doc.id, "filename": doc.filename, "type": doc.type, "created_at": doc.created_at} for doc in documents]


@app.get("/projects/{project_id}/documents/{document_id}")
def get_document(project_id: int, document_id: int, db: Session = Depends(get_db)):
    doc = db.query(models.Document).filter(
        models.Document.id == document_id, 
        models.Document.project_id == project_id
    ).first()
    
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")
        
    return {"id": doc.id, "filename": doc.filename, "type": doc.type, "content": doc.content}