from typing import Optional, List
from fastapi import FastAPI, Depends, UploadFile, File
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.orm import Session
from pydantic import BaseModel

import models
from database import engine, get_db

models.Base.metadata.create_all(bind=engine)

app = FastAPI()

origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ProjectCreate(BaseModel):
    name: str
    description: Optional[str] = None

class ProjectResponse(BaseModel):
    id: int
    name: str
    description: Optional[str] = None

    class Config:
        from_attributes = True # Allows Pydantic to read SQLAlchemy objects


@app.get("/")
def root():
    return {"message": "SQLAlchemy Backend is running!"}

@app.post("/projects/", response_model=ProjectResponse)
def create_project_route(project: ProjectCreate, db: Session = Depends(get_db)):
    # Create the SQLAlchemy object
    new_project = models.Project(name=project.name, description=project.description)
    
    db.add(new_project)
    db.commit()
    db.refresh(new_project) # Get the new ID generated by SQLite
    return new_project

@app.get("/projects", response_model=List[ProjectResponse])
def get_projects_route(db: Session = Depends(get_db)):

    projects = db.query(models.Project).order_by(models.Project.id.desc()).all()
    return projects

@app.post("/projects/{project_id}/documents/")
async def upload_documents(project_id: int, files: List[UploadFile] = File(...), db: Session = Depends(get_db)):
    uploaded_names = []
    
    for file in files:
        # 1. Read the file
        content = await file.read()
        text_content = content.decode("utf-8") 
        
        # 2. Create the Document object
        new_doc = models.Document(
            project_id=project_id,
            filename=file.filename,
            content=text_content
        )
        
        db.add(new_doc)
        uploaded_names.append(file.filename)
        
    # Commit all files to the database at once!
    db.commit()
    
    return {"message": f"Successfully uploaded {len(uploaded_names)} files!", "files": uploaded_names}

@app.get("/projects/{project_id}/documents/")
def get_project_documents(project_id: int, db: Session = Depends(get_db)):
   
    documents = db.query(models.Document).filter(models.Document.project_id == project_id).all()
    
    return [{"id": doc.id, "filename": doc.filename, "created_at": doc.created_at} for doc in documents]